[tool.poetry]
name = "aiogram-v3-template"
version = "0.1.0"
description = ""
authors = ["Timur Kerimov <tim-online@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^3.10.0"
pydantic-settings = "^2.3.4"
pydantic = "^2.8.2"
cachetools = "^5.3.3"
redis = "^5.0.7"

[tool.poetry.group.dev.dependencies]
betterlogging = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
