[tool.poetry]
name = "Telegram Bot"
version = "0.1.0"
description = ""
authors = ["Timur Kerimov <tim-online@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^3.10.0"
pydantic-settings = "^2.3.4"
pydantic = "^2.8.2"
cachetools = "^5.3.3"
redis = "^5.0.7"
types-cachetools = "^5.3.0.7"

[tool.poetry.group.dev.dependencies]
betterlogging = "^1.0.0"
mypy = "^1.10.1"
ruff = "^0.5.1"

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
follow_imports = "normal"
show_error_context = true
pretty = true
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "tgbot.handlers.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
